---
- hosts: localhost
  become: no
  gather_facts: false
  
  tasks:

  - name: Download Consul Package
    get_url:
      url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
      dest: /tmp


- hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: Unarchive Consul Binary
    unarchive:
      src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
      dest: "{{ consul_binary_directory }}"

  - name: Create Consul Bootstrap Directory
    file:
      path: "{{ consul_bootstrap_directory }}"
      state: directory

  - name: Create Consul Servers List
    set_fact:
      consul_list: >-
        {% set consul_servers_list = [] %}
        {% for host in groups['servers'] %}
        {{ consul_servers_list.append('"' + hostvars[host].advertise_ip + ':' + '8301' + '"') }}
        {% endfor %}
        {{ consul_servers_list|unique|join(', ') }}

  - name: Create Consul Config File
    template:
      src: config.json.j2
      dest: "{{ consul_bootstrap_directory }}/config.json"

  - name: Create Consul systemd config file
    template:
      src: consul.service.j2
      dest: /etc/systemd/system/consul.service

  - name: Restart Consul service
    systemd:
      name: consul
      state: restarted
      daemon_reload: true
